name: 'Jeremy Koch'

title: 'Jeremy Koch'
description: 'A place for code, design, and any other random thoughts.'
bio: 'Engineer at IBM. Designs and builds beautiful products. Codes in Swift. Sexying up the enterprise.'
timezone: America/Los_Angeles

markdown: kramdown
highlighter: rouge
kramdown:
   input: GFM
   syntax_highlighter: rouge

logo: false
paginate: 8
domain_name: 'https://jerkoch.com'
google_analytics: 'UA-52909708-2'

url: 'https://jerkoch.com'
baseurl: /

author: jerkoch
author_location: 'Davis, California'
author_link: https://twitter.com/jerkoch

twitter:
  username: jerkoch

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.jpg

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

social_links:
  twitter: 'https://twitter.com/jerkoch'
  github: 'https://github.com/jerkoch/'
  linkedin: 'https://www.linkedin.com/in/jerkoch'
