name: Jeremy Koch
description: "Just another hacker, changing the world, one line of code at a time."
meta_description: "Your New Jekyll Site, Blogging about stuffs"
bio: "Software engineer with 20 years of expertise designing and building full-stack solutions. Currently focused on  + IBM, Swift, and bringing exciting new apps to the enterprise."
markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jerkoch.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://jerkoch.com'
author:         'Jeremy Koch'
