name: Jeremy Koch
description: "Engineer at IBM. Designs and builds beautiful products. Codes in Swift. Sexying up the enterprise."
meta_description: "Your New Jekyll Site, Blogging about stuffs"
bio: "Engineer at IBM. Designs and builds beautiful products. Codes in Swift. Sexying up the enterprise."
markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jerkoch.com'
google_analytics: 'UA-XXXXXXXX-X'

url: 'http://jerkoch.com'
author: 'Jeremy Koch'
author_location: 'Davis, California'
author_link: http://twitter.com/jerkoch