name: Jeremy Koch
description: "Engineer at IBM. Designs and builds beautiful products. Codes in Swift. Sexying up the enterprise."
bio: "Engineer at IBM. Designs and builds beautiful products. Codes in Swift. Sexying up the enterprise."
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
future: true
domain_name: 'https://jerkoch.com'
google_analytics: 'UA-52909708-2'

url: 'https://jerkoch.com'
author: jerkoch
author_location: 'Davis, California'
author_link: https://twitter.com/jerkoch

twitter:
    username: jerkoch

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.jpg

gems: [jekyll-paginate, jekyll-seo-tag]

